name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false 
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      timeout-minutes: 15
      with:
        version: '6.8.0'  # 6.8.3 might not be available yet
        cache: true
        cache-key-prefix: ${{ runner.os }}-qt  # Separate cache per OS
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Package Windows Application with Qt DLLs
      if: runner.os == 'Windows'
      run: |
        mkdir deploy
        cp build/Release/Gomoku.exe deploy/
        windeployqt deploy/Gomoku.exe --release --no-translations
      shell: bash
    
    - name: Upload artifacts (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: gomoku-${{ matrix.os }}
        path: deploy/
    
    - name: Upload artifacts (Unix)
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: gomoku-${{ matrix.os }}
        path: build/Gomoku
